# Generated by Django 3.2 on 2021-04-26 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('deliver', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_till', models.TimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('city', models.ManyToManyField(to='core.City')),
                ('facilities', models.ManyToManyField(null=True, to='core.Facility')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Volunteers',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('deliver_at_doorstep', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_verification', models.BooleanField(default=False)),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('request_edit', models.BooleanField(default=False)),
                ('edit', models.TextField(blank=True, null=True)),
                ('city', models.ManyToManyField(to='core.City')),
                ('facility', models.ManyToManyField(to='core.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('total_oxygen_beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_ventilators', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_icu', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available_oxygen_beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available_ventilators', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available_icu', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_verification', models.BooleanField(default=False)),
                ('emergency_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('request_edit', models.BooleanField(default=False)),
                ('edit', models.TextField(blank=True, null=True)),
                ('city', models.ManyToManyField(to='core.City')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('alternate_mobile', models.CharField(blank=True, max_length=16, null=True)),
                ('experience', models.TextField()),
                ('experienced_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state'),
        ),
    ]
